# Generated by Django 6.1 on 2026-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('release_date', models.CharField(blank=True, max_length=32)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
                ('symbol_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
