# Generated by Django 6.1 on 2026-08-14 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pokemonset'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.offer'),
        ),
    ]
