# Generated by Django 6.1 on 2026-08-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_offer_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='recipient_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('countered', 'Countered'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
