SANTIAGO_PLACES = [
    'Santiago Centro',
    'Providencia',
    'Las Condes',
    'Vitacura',
    'Ñuñoa',
    'La Florida',
    'Maipú',
    'Puente Alto',
    'San Bernardo',
    'Peñalolén',
    'La Reina',
    'Recoleta',
    'Independencia',
    'Estación Central',
    'Quinta Normal',
    'Macul',
    'San Joaquín',
    'La Cisterna',
    'Pedro Aguirre Cerda',
    'Cerro Navia',
    'Conchalí',
    'Huechuraba',
    'Quilicura',
    'Renca',
    'Lo Barnechea',
    'Cerrillos',
    'Lo Espejo',
    'El Bosque',
    'La Granja',
    'San Ramón',
    'Lo Prado',
    'Pudahuel',
]